### ISSUE TITLE
Beast Men Patch

### ISSUE THREAD

**Issue by Diamonddragon41** [kpqi5858/AlienFaces_Dev#1]
[AlienPatchNew.zip](https://github.com/kpqi5858/AlienFaces_Dev/files/2622416/AlienPatchNew.zip)

Here's the new AlienPatch.xml. Just added stuff for the beastmen at the bottom. I should mention I allowed all hairs in the game to be drawn onto beast men races with some of those alien faces options. However, in the original mod, they can only have two (rather meh looking) hairstyles from the mod drawn on them. You might want to mention that in case users like or dislike that change.

**Comment by kpqi5858** [comment]
Thanks for the patch, I merged it
